---
title: "Visual Analytics of Tanzania Tourist Spending"
author: "Habari Tanzania"
---

Habari Tanzania

The Tanzanian tourism sector plays a significant role in the Tanzanian economy, contributing about 17% to the country's GDP and 25% of all foreign exchange revenues. The sector, which provides direct employment for more than 600,000 people and up to 2 million people indirectly, generated approximately \$2.4 billion in 2018 according to government statistics. Tanzania received a record 1.1 million international visitor arrivals in 2014, mostly from Europe, the US and Africa.

Tanzania is the only country in the world which has allocated more than 25% of its total area for wildlife, national parks, and protected areas.There are 16 national parks in Tanzania, 28 game reserves, 44 game-controlled areas, two marine parks and one conservation area.

Tanzania's tourist attractions include the Serengeti plains, which hosts the largest terrestrial mammal migration in the world; the Ngorongoro Crater, the world's largest intact volcanic caldera and home to the highest density of big game in Africa; Kilimanjaro, Africa's highest mountain; and the Mafia Island marine park; among many others. The scenery, topography, rich culture and very friendly people provide for excellent cultural tourism, beach holidays, honeymooning, game hunting, historical and archaeological ventures -- and certainly the best wildlife photography safaris in the world.

The objective of this project is to understand the behaviors behind tourists spending and how different factors affect tourist spending. The secondary objective is to develop a machine learning model to predict what a tourist will spend when visiting Tanzania.These findings can be used by different tour operators and the Tanzania Tourism Board to automatically help tourists across the world estimate their expenditure before visiting Tanzania.

The data for the analysis is extracted from [here](https://zindi.africa/competitions/tanzania-tourism-prediction-challenge/data).
