---
title: "Exploratory Data Analysis"
author: "Habari Tanzania"
date: 14 Feb 2023
date-modified: "`r Sys.Date()`"
execute: 
  echo: true
  eval: true
  warning: false
format: html
editor: visual
---

```{r}
pacman::p_load("ggstatsplot", "plotly", "DT", "scales","tidyverse")
```

## 2. Loading the data

```{r}
touristdata_clean <- read_csv("data/touristdata_clean.csv")
touristdata_clean <- touristdata_clean %>%
  filter(total_cost > 0,
         total_tourist > 0,
         total_night_spent > 0) %>%
  mutate(cost_per_pax = round(total_cost/total_tourist,0),
         cost_per_night = round(total_cost/total_night_spent,0),
         cost_per_pax_night = round(total_cost/total_tourist/total_night_spent,0))
```

## 3. Correlation

```{r}
options(scipen = 999)


ggscatterstats(data = touristdata_clean,
                 x = cost_per_pax, y = total_night_spent,
                 type = "nonparametic") + facet_wrap(~main_activity)

ggscatterstats(data = touristdata_clean,
                 x = cost_per_pax, y = total_night_spent,
                 type = "nonparametic") + facet_wrap(~travel_with)

ggscatterstats(data = touristdata_clean,
                 x = cost_per_pax, y = total_night_spent,
                 type = "nonparametic") + facet_wrap(~age_group)

ggscatterstats(data = touristdata_clean,
                 x = cost_per_pax, y = total_night_spent,
                 type = "nonparametic") + facet_wrap(~tour_arrangement)

```

```{r}

plotcorrelation_costppvtn <- function (a) {
ggscatterstats(data = touristdata_clean,
                 x = cost_per_pax, y = total_night_spent,
                 type = "nonparametic") + facet_wrap(vars(!!sym(a)))
}

plotcorrelation_costppvtn ("tour_arrangement")
  
  
```


```{r}
plotcorrelation_costppvtn ("age_group")
```

```{r}
plotcorrelation_costppvtn ("travel_with")
```
```{r}
plotcorrelation_costppvtn ("main_activity")
```

```{r}
plotcorrelation_costppvtn ("purpose")
```

```{r}
plotcorrelation_costppvtn ("info_source")
```